name: ci
on: 
  [push, pull_request]
jobs:
  build:
    name: Tests
    runs-on: ubuntu-latest
    steps:
      - name: Checkout 🛎
        uses: actions/checkout@v1

      - name: Install dependencies 📦
        uses: cypress-io/github-action@v1
        with:
          runTests: false

      - name: Build 🏗
        run: npm run build

      - name: ng7 example 💎
        uses: cypress-io/github-action@v1
        with:
          working-directory: examples/ng7

      - name: ngx example 💎
        uses: cypress-io/github-action@v1
        with:
          working-directory: examples
      
      - name: Upload artifact ngx
        if: ${{ always() }}
        uses: actions/upload-artifact@v2
        with:
          name: artifact-ngx
          path: |
            **/screenshots/**/*(failed).png
            **/init.diff.png